### ISSUE TITLE
Question about faceting 

### ISSUE THREAD

**Issue by ymkng** [ArnaudDroitLab/metagene2#19]
Hello, I'm trying to use the "facet_by" function in metagene2 and I'm stuck on how to do that. I want to facet by regions (so one graph showing "upstream" and one graph showing "downstream").

<img width="850" alt="Screen Shot 2019-05-28 at 11 55 55 AM" src="https://user-images.githubusercontent.com/37229946/58505639-4790b000-8142-11e9-803c-3ddfc1aed9a1.png">

**Comment by ericfournier2** [comment]
Hello ymkng,

facet_by should be a formula using columns from your region_metadata data.frame. In your case, that would be the "meta" column you created.

```r
YSC178_dupremoved_upstream_pos$plot(facet_by=~meta)
```

But you're giving yourself a lot of unnecessary trouble by specifying region_metadata. Since your regions are in bed files, metagene2 is already creating the region_name meta-column for you. Also, you don't need to call group_coverages or plot explicitly. produce_metagene takes care of everything.

```r
YSC178_dupremoved_upstream_pos <- metagene2$new(
    regions=c("upstreamTRNApos.bed", "downstreamTRNApos.bed"), 
    bam_files=c( ...),
    extend_reads=20)
YSC178_dupremoved_upstream_pos$produce_metagene(bin_count=500, 
    normalization="RPM", 
    facet_by=~region_name, 
    title="Merged_YSC178_YSC180_YSC185dupremoved upstream positive strand")
```
Also, since you're facetting by region type, you probably want to also use the group_by option so that your legend only has your bam files/designs instead of bam_files + region_type combination:
```r
YSC178_dupremoved_upstream_pos <- metagene2$new(
    regions=c("upstreamTRNApos.bed", "downstreamTRNApos.bed"), 
    bam_files=c( ...), 
    extend_reads=20)
YSC178_dupremoved_upstream_pos$produce_metagene(
    bin_count=500, normalization="RPM", 
    facet_by=~region_name, 
    group_by="design", 
    title="Merged_YSC178_YSC180_YSC185dupremoved upstream positive strand")
```

As an aside, it's more practical to copy-paste your code into issues rather than screenshotting it, this way it's easier for us to edit it to make suggestions.

Hope this helps,
-Eric

**Comment by ymkng** [comment]
thank you so much it works now!!
